### PR TITLE
added scrollView and padding

### PR DESCRIPTION
**Pull request by Ravneet5911**

### CODE REVIEW

**Review by johnmahlon — APPROVED** [review]
Looks good, and scrolling is a fine solution. Thanks for working on this!

**Comment by Ravneet5911** [comment]
Welcome @johnmahlon 
I have a suggestion for you that you can change one more thing in this app that when we click the textField the keyboard shows up and you can also put alphabets in it. You should let the textField accept only number Values.
If you are interested to do this, then let me know I can do this for you.

**Comment by johnmahlon** [comment]
@Ravneet6041 yeah this is true. Definitely feel free to open an issue/PR for it and I'll check it out again. Thanks for working on this!

**Comment by Ravneet5911** [comment]
@johnmahlon may be I can solve this issue so, if you want to open this issue then open it and assign me.

**Pull request merged**
